- lib/unleash/client.rb
- lib/unleash/metrics_reporter.rb
- lib/unleash/toggle_fetcher.rb
Prior to this change connecting to an unleash server over https would result in an exception.
> Fix connecting to unleash servers over https

- lib/unleash/client.rb
- lib/unleash/configuration.rb
- lib/unleash/metrics_reporter.rb
- lib/unleash/toggle_fetcher.rb
- spec/unleash/client_spec.rb
- spec/unleash/configuration_spec.rb
This should be a proper fix for #10
> Add missing HTTP headers

- .travis.yml
- README.md
- lib/unleash/client.rb
- lib/unleash/configuration.rb
- spec/unleash/client_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash_spec.rb
- unleash-client.gemspec
This can be useful if you are testing you application in an automated way, and
neither want to have unleash configured, nor have it ever attempt to connect
to a remote host.
> Add option/support for making this unleash client completely dummy.

- lib/unleash/feature_toggle.rb
- spec/unleash/feature_toggle_spec.rb
After test the result combinations with default result, it does not work as expected when default value is true. It will always override combined result as true regardless the combined result of toggle is enabled and strategy result.
https://github.com/Unleash/unleash-client-ruby/blob/master/lib/unleash/feature_toggle.rb#L74..L81
The modification will be - when strategy result already computed and toggle is enabled, it may respect that combined result instead of default result.
> Default result always override result when it set as true

- README.md
- lib/unleash/client.rb
configuration setting was never sent to ScheduledExecutor
> #31 - bugfix: respect retry_limit configuration parameter

- .rubocop.yml
- .travis.yml
- lib/unleash/activation_strategy.rb
- lib/unleash/constraint.rb
- lib/unleash/context.rb
- lib/unleash/feature_toggle.rb
- lib/unleash/strategy/flexible_rollout.rb
- lib/unleash/strategy/gradual_rollout_sessionid.rb
- lib/unleash/strategy/gradual_rollout_userid.rb
- spec/unleash/activation_strategy_spec.rb
- spec/unleash/constraint_spec.rb
- spec/unleash/feature_toggle_spec.rb
- spec/unleash/strategy/flexible_rollout_spec.rb
I should consider adding more tests in the flexible_rollout_spec.rb
> #26, #27 - Implement Strategy Constraints and FlexibleRollout Strategy

- lib/unleash/toggle_fetcher.rb
I was getting a bit annoyed at an error the unleash client was putting in my console whenever I was doing local dev on my windows machine for a website I'm working on.
I've found windows to be very particular when it comes to file operations and it was complaining about permissions whenever I ran my site or even just a rake command
```
E, [2020-12-08T16:10:54.775034 #18340] ERROR -- : Unable to save backup file. Exception thrown Errno::EACCES:'Permission denied @ rb_file_s_rename - (C:/Users/Alex/AppData/Local/Temp/unleash--repo.json.tmp, C:/Users/Alex/AppData/Local/Temp/unleash--repo.json)'
E, [2020-12-08T16:10:54.775427 #18340] ERROR -- : stacktrace: ["C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/unleash-3.2.0/lib/unleash/toggle_fetcher.rb:74:in `rename'", …
```
> Windows File permissions fix

- unleash-client.gemspec
This is just recreating PR #43 into a separate branch, instead of going directly to master.
> Update ruby_version requirement to allow Ruby 3.0

- .rubocop.yml
- README.md
- lib/unleash/client.rb
- spec/unleash/client_spec.rb
> Allow passing blocks to is_enabled? to determine default_result (#33)

- README.md
- examples/simple.rb
to comply with v4 requirements for SDK,.
> fix: add api token to getting started example

- lib/unleash/configuration.rb
- lib/unleash/toggle_fetcher.rb
- spec/unleash/configuration_spec.rb
This happened when the configuration for app_name is done via yield, and
we did not allow app_name changes to be reflected in the backup_file.
Added unit tests to catch this bug.
> fix: backup_file config setting being incorrectly set (#56)

- .rubocop.yml
- spec/unleash/context_spec.rb
make it explicit the current state of matching.
It would be good to have this PR merged before #69  as this includes tests for some use-cases that are affected there.
> tests: make tests pass in context matching

- lib/unleash/context.rb
- spec/unleash/context_spec.rb
Fix an issue where camel case property values being resolved in the context object would incorrectly raise a KeyError
> fix: Allow context to correctly resolve camelCase property values

- .github/workflows/pull_request.yml
- lib/unleash/feature_toggle.rb
- lib/unleash/strategy/flexible_rollout.rb
- lib/unleash/variant_definition.rb
- spec/unleash/client_spec.rb
- spec/unleash/context_spec.rb
- spec/unleash/feature_toggle_spec.rb
- spec/unleash/strategy/flexible_rollout_spec.rb
- Add custom stickiness for feature variants
- Add custom stickiness for flexible rollout strategies
- Implement custom stickiness property on variant defs
- Force context to resolve to nil instead of crashing with empty props
> feat: Implement custom stickiness

- bin/unleash-client
Important to allow using the `Authorized` HTTP header with the utility (as it is now a required parameter).
also other minor cosmetic improvements.
> (feat) Allow using custom_http_headers from the CLI utility

- .rubocop.yml
- lib/unleash.rb
- lib/unleash/client.rb
- lib/unleash/metrics_reporter.rb
- spec/unleash/client_spec.rb
- spec/unleash/metrics_reporter_spec.rb
We want to preserve the backend from having to work, when there is no work to be done.
> fix: only send metrics if there is data to send. (#58)

- README.md
- lib/unleash/configuration.rb
- spec/unleash/configuration_spec.rb
to the same values used in the other SDKs
> chore: standardize default values for metrics_interval and retry_limit

- .github/workflows/pull_request.yml
- README.md
and document that it is a supported version
> chore: add ruby 3.1 support in gh actions

- README.md
- lib/unleash/configuration.rb
- spec/unleash/configuration_spec.rb
By default the client will disable itself after 5 failing API hits, this PR changes this default behaviour to never disable
> Default to never disable after failure

- lib/unleash/client.rb
- lib/unleash/feature_toggle.rb
- spec/unleash/client_specification_spec.rb
- spec/unleash/feature_toggle_spec.rb
The incumbent behaviour of feature toggles when they are present but disabled, and the default value was set to true, seemed to be incorrect - it would resolve to true, using the default value, rather than the value of the existing toggle. This meant that, for example (in the case of using the default strategy), code like `UNLEASH.is_enabled?('my-feature-toggle', context, true)` will always resolve to true regardless of the value of the toggle itself.
It doesn't seem correct that code within the feature toggle resolution code was taking default values - if a feature toggle is present, the default value shouldn't be relevant, so far as I understand the intent behind specifying a default value.
This PR corrects the assertions made in the tests for feature toggles, and corrects the behaviour …
> correct logic for default values on feature toggles

- lib/unleash/toggle_fetcher.rb
- spec/unleash/toggle_fetcher_spec.rb
We introduced this excellent gem, in a project of ours and noticed these strange errors in the logs:
```
ToggleFetcher ERROR] : thread ToggleFetcher threw exception NoMethodError  (1/Infinity): 'undefined method `close' for <Rake::FileTask  => []>:Rake::FileTask
file&.close if defined?(file)
^^^^^^^
```
It turned out that the file variable was out of scope for the ensure block in the `Unleash::ToggleFetcher#save!` and in this case it was referring to a DSL method in the rake gem.
https://github.com/ruby/rake/blob/881416e322d597e47e62935ef6a9dbaed934fbfc/lib/rake/dsl_definition.rb#L76
This revealed some problems when closing the file in the ToggleFetcher.
Changes the way the file is closed in `Unleash::ToggleFetcher#save!`.
The ensure block didn't previously close the file because the …
> Ensure backup file is properly closed.

- README.md
- examples/bootstrap.rb
- examples/simple.rb
Changes references of `http://unleash.herokuapp.com/api` to be https in README and examples.
Mentioned as a review comment in https://github.com/Unleash/unleash-client-ruby/pull/107
> Update http to https in README and examples

- README.md
- lib/unleash/configuration.rb
- spec/unleash/configuration_spec.rb
Add support for dynamic `custom_http_headers` by allowing passing a Proc/Lambda as the configuration.
We also removed and unnecessary duplication from the `http_headers` method.
Closes #83 
We removed a redundant method `ensure_valid_opts` that was called in the constructor. This method was also out of sync with the `Configuration#validate!` by allowing nil. We ensured that `Configuration#validate!` was called in the places where it's needed before removing this method.
> Add dynamic headers support

- .rspec
- spec/unleash/activation_strategy_spec.rb
- spec/unleash/bootstrap/handler_spec.rb
- spec/unleash/bootstrap/provider/from_file_spec.rb
- spec/unleash/client_spec.rb
- spec/unleash/client_specification_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/constraint_spec.rb
- spec/unleash/context_spec.rb
- spec/unleash/metrics_reporter_spec.rb
- spec/unleash/metrics_spec.rb
- spec/unleash/scheduled_executor_spec.rb
- spec/unleash/strategy/application_hostname_spec.rb
- spec/unleash/strategy/base_spec.rb
- spec/unleash/strategy/default_spec.rb
- spec/unleash/strategy/flexible_rollout_spec.rb
- spec/unleash/strategy/gradual_rollout_random_spec.rb
- spec/unleash/strategy/gradual_rollout_sessionid_spec.rb
- spec/unleash/strategy/gradual_rollout_userid_spec.rb
- spec/unleash/strategy/remote_address_spec.rb
- spec/unleash/strategy/user_with_id_spec.rb
- spec/unleash/strategy/util_spec.rb
- spec/unleash/toggle_fetcher_spec.rb
- spec/unleash/variant_override_spec.rb
- spec/unleash_spec.rb
Require the spec_helper file globally when running tests so it's not required to be included first in every test file. This would be a first step towards implementing some defaults as discussed in https://github.com/Unleash/unleash-client-ruby/pull/97#discussion_r865787364
It also makes it easier to contribute changes because there is no need to know which files are required to be imported in the test context.
Not every project uses this approach and it's more of a preference which method is used.
> Require spec_helper in the .rspec file

- lib/unleash/constraint.rb
- spec/unleash/constraint_spec.rb
This makes it possible to have int values in context and compare it to sets from unleash which are strings.
> fix: support int context in set comparison

- .github/workflows/pull_request.yml
- .rubocop.yml
- lib/unleash.rb
- lib/unleash/activation_strategy.rb
- lib/unleash/client.rb
- lib/unleash/configuration.rb
- lib/unleash/feature_toggle.rb
- lib/unleash/toggle_fetcher.rb
- spec/unleash/client_specification_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/toggle_fetcher_spec.rb
This implements global segments as per issue #112. There is one major deviation from the way this is implemented in other SDKs, this doesn't use a lazy generator, this is because this SDK doesn't cache computation as aggressively as the other SDKs.
Most of the tests are done through the client specifications but there's also some failing tests here, these aren't caused by this PR, but by upgrading the client specs. There's another PR incoming to fix that.
> feat: implement global segments

- README.md
- lib/unleash.rb
- lib/unleash/client.rb
- lib/unleash/configuration.rb
- lib/unleash/feature_toggle.rb
- lib/unleash/strategies.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/strategies_spec.rb
- spec/unleash_spec.rb
Other clients and proxy allows implementation and usage of [custom activation strategies](https://docs.getunleash.io/advanced/custom_activation_strategy). This pull request provides easy way for ruby client to be extend with those strategies. 
Previous state:
- Strategies constructed at runtime into a constant.
- Strategies have duplicated logic for strategy name (method, initialization code)
- Strategies matched by converting everything into symbol
- Strategies stored as hash and force clients to work with hash
Pull Request:
- Wraps strategies management mechanism into simple interface
- Using strategy `name` method as single source of identification
- Allows adding new strategies at runtime
- Changes strategy construction from reflection to simple list (default strategies are not …
> Allow custom strategies

- .rubocop.yml
- lib/unleash/configuration.rb
- lib/unleash/strategy/flexible_rollout.rb
- lib/unleash/strategy/gradual_rollout_sessionid.rb
- lib/unleash/strategy/gradual_rollout_userid.rb
- lib/unleash/strategy/remote_address.rb
- lib/unleash/strategy/user_with_id.rb
- lib/unleash/variant_definition.rb
- lib/unleash/variant_override.rb
- unleash-client.gemspec
Updates the RuboCop version to version 1.28.2. RuboCop 1.28 is the latest version to still support Ruby 2.5.
This is the version that was intended to be used but the build was broken and after it was fixed in https://github.com/Unleash/unleash-client-ruby/pull/101 we can now update the version and fix the RuboCop errors.
* .rubocop.yml
* lib/unleash/variant_definition.rb
> Update RuboCop version

- lib/unleash/client.rb
This pr makes initiating unleash like this work again:
```
@unleash = Unleash::Client.new(
url: 'https://unleash.herokuapp.com/api',
custom_http_headers: { 'Authorization': '943ca9171e2c884c545c5d82417a655fb77cec970cc3b78a8ff87f4406b495d0' },
app_name: 'simple-test',
instance_id: 'local-test-cli',
refresh_interval: 2,
metrics_interval: 2,
retry_limit: 2
)
```
> Fixes constructor

- .rubocop.yml
- lib/unleash/context.rb
- spec/unleash/client_spec.rb
- spec/unleash/strategy/user_with_id_spec.rb
We should pass user_id as a string in Unleash::Context to make it work. In most cases user_id is an integer, so we have to convert the id into an integer. It's a little annoying to do it all the time.
> fix: add possibility to passing user_id as integer

- lib/unleash/metrics.rb
The simplest way to guarantee correctness across threads is by synchronising / protecting concurrent data access/change using a mutex, as it is done in the toggle fetcher.
Add locks around data access/changes in the metris reporting data structure. Should have been in place a long time ago. Brought to my attention in PR #121. However the solution proposed there is also not thread-safe. Though it might prevent the exception, it will most definitely not prevent concurrency issues.
Closes #121 
`metrics.rb` 🙂 
This change should have been implemented a long time ago, as was noted in line 5 (`# NOTE: no mutexes for features`). 
This slows down the gathering of metrics, which is in the critical path when evaluating features/variants to about half the speed. Don't think that it matters as much …
> fix: prevent race condition when manipulating metrics data

- .github/workflows/pull_request.yml
- README.md
Be explicit about jruby 9.4 being supported. See https://www.jruby.org/2022/11/23/jruby-9-4-0-0
Also update a gha step, to avoid warning messages in the build.
> Chore: Add support for jruby 9.4

- .rubocop.yml
- README.md
- lib/unleash/client.rb
- spec/unleash/client_spec.rb
Adding `disabled?` method to more comfort using Unleash.
> Adding disabled? method

- unleash-client.gemspec
This ensures that murmurhash3 will work correctly with native libraries on current Rubygems versions, see
https://github.com/funny-falcon/murmurhash3-ruby/issues/10
The `murmurhash3` native library is broken on recent versions of Rubygems (3.4+) and causes the following warning:
```
Attention: used pure ruby version of MurmurHash3
``` 
The `murmerhash3` gem has been updated with a fix, and updating this dependency ensures the updated version will be installed.
See:
- https://github.com/funny-falcon/murmurhash3-ruby/issues/10
- https://github.com/rubygems/rubygems/issues/6205
> Update murmurhash3 minimum version to 0.1.7

- README.md
This change removes any references to setting `environment` in the SDK
config manually.
It also updates the config property description to clarify that it is
not the same as the "Unleash environment".
Why? Because this is a returning point of confusion for our users,
The config option description says "not yet in use". Is still true?
> docs: remove refs to `environment` in samples, update description

- README.md
- lib/unleash/client.rb
- spec/unleash/client_spec.rb
Disabling the client is meant for when a user will be testing their code, and no connection to a remote server is desired.
It is hard to see a use case for collecting and reporting metrics if the client is disabled. Forcefully disabling metrics when disabling the client makes sense and is a more coherent behavior.
Closes #139
Note that this change does change behavior, but to make things more sane.
* `client.rb`
* `client_spec.rb`
Also added `WebMock.reset!` in the `client_spec.rb` to ensure no leakage between tests.
Maybe it would have made more sense to have it overridden in `lib/unleash/configuration.rb` (by moving `disable_metrics` from `attr_accessor` to `attr_writter` + own getter) ?
> fix: forcefully disabling metrics when client is disabled (#139)

- lib/unleash/client.rb
- lib/unleash/feature_toggle.rb
- spec/unleash/client_spec.rb
Attempts to address #137
Variants in a bootstrap configuration are ignored with the client is disabled. These changes remove that limitation, so disabled clients can interact with bootstrapped variants.
**Auxiliary changes:**
Calling `get_variant` allows passing a nil context, however attributes of this context are referenced when calculating the variant salt resulting in `undefined method ... for nil` errors. Account for a nil context in this method which results in the default: random number.
> Allow bootstrapped variants when client is disabled

- lib/unleash/context.rb
- spec/unleash/feature_toggle_spec.rb
Should be merged ONLY after #138, #142 are merged.
Adds test cases that #138 did not cover. #138 should soon have the fix in `feature_toggle.rb` that is included here. (but I  will be remove from this PR when rebasing once #138 is merged). The fix is included here to show that the tests fail w/o it, and pass with it.
Also added a comment in `get_by_name()` in `context.rb` as a reminder that it will throw exceptions when a key is not found (IIRC by design).
PR #142 fixes the rubocop issues found here.
Kudos to @jdurkee-mdsol for finding the bug where we didn't handle the case for get_variant when the context wasn't valid.
> Fix handling of invalid context in get_variant

- .github/workflows/pull_request.yml
- .rubocop.yml
- spec/unleash/constraint_spec.rb
- spec/unleash/feature_toggle_spec.rb
- unleash-client.gemspec
Update development gems.
Unfortunately these changes are tightly coupled, so a smaller PR is not really feasible.
Updated github actions/checkout  to a supported version.
Updated `Metrics/ClassLength` in rubocop config so PR in #138 should not fail.
Note that rubocop now will only work on supported versions of ruby. Given that this is only for when developmening/testing, it should be fair to have the `if RUBY_VERSION` around it, even if in principle that's not ideal. The other option would be to stop supporting ancient versions of ruby, but that's not an adequate trade-off. 
Linted some code so the new rubopcop is happy.
> chore: update gems: rspec, webmock and rubocop

- CHANGELOG.md
- README.md
SSIA
Closes #79 && #94
1) Would like feedback from the Unleash team regarding the use of Changelog (see #79 ).
It is only useful if it is kept up-to-date, so it does require a bit more effort in documenting changes. Not sure what is the practice in the other SDKs, or if you guys have opinions regarding this. (maybe referring to the gitlog is a good enough policy?) 
Only went back to release 4.0.0 when recreating the changelog history.
2) Also thought it would be nice to clarify the steps when creating a new release.
Thought it would be nice to have these in place before creating the next release. :slightly_smiling_face:
> chore: docs: Add Changelog and update docs sections on releasing and contributing (#79) (#94)

- lib/unleash/strategy/flexible_rollout.rb
- spec/unleash/strategy/flexible_rollout_spec.rb
The flexible rollout strategy should evaluate default and random stickiness even if context is not provided.
> fix: flexible rollout strategy without context

- .github/workflows/pull_request.yml
- README.md
- lib/unleash/activation_strategy.rb
- lib/unleash/feature_toggle.rb
- lib/unleash/variant_definition.rb
- spec/unleash/activation_strategy_spec.rb
- spec/unleash/feature_toggle_spec.rb
Description
Implementation of Strategy Variants
Type of change
Please delete options that are not relevant.
New feature (non-breaking change which adds functionality)
How Has This Been Tested?
By running specifications locally
> variants in strategies

- .github/workflows/pull_request.yml
- README.md
We added some specifications for some edge cases. The ruby sdk supports this, but nice to have updated the client specifications
> chore: update client-specifications to 4.3.3

- lib/unleash/feature_toggle.rb
This is just a simple refactor PR, to make use of `Struct` more idiomatic (introducted in PR #148).
There is also one typo in a prosa fixed as well.
> refactor: FeatureEvaluationResult struct as object

- README.md
Markdown generators (including GitHub) tend to lowercase the titles
when they create anchor links. Most browsers might be able to handle
mixed case, but some of our tools don't.
Update: this was not breaking the docs build for Unleash. I was wrong. The docs build issue was a separate issue entirely.
However, this does seem to cause issues with the link on the rendered doc, as the browser can't find it correctly, so lowercasing it isn't a bad thing. That said, that should be handled by the doc generator going forward, and there is a [PR to do just that](https://github.com/Unleash/unleash/pull/4963).
> docs: lowercase link to installation section of readme

- spec/unleash/client_specification_spec.rb
This is a prerequisite for testing the next version of the client specifications.
Currently the client specifications are running using the internals of the SDK, this makes them use the unleash_client instead.
> refactor: use unleash client to run client specifications

- .github/workflows/pull_request.yml
- .rubocop.yml
- README.md
- lib/unleash/client.rb
- lib/unleash/configuration.rb
- lib/unleash/feature_toggle.rb
- spec/unleash/client_specification_spec.rb
- spec/unleash/configuration_spec.rb
This pr implements dependant feature toggles. The tests are specified in the client specifications https://github.com/Unleash/client-specification/pull/63
> feat: dependant toggles

- .rubocop.yml
- examples/extending_unleash_with_opentelemetry.rb
this must be added before starting the unleash client. (in a rails initializer for example).
This is added as future reference/documentation for the solution to PR https://github.com/Unleash/unleash-client-ruby/pull/150
Few will use opentelemetry, but it is nice to have to something to point to for those that use it.
> docs/example: add example on how to add opentelemetry headers/support

- lib/unleash/configuration.rb
- spec/unleash/client_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/metrics_reporter_spec.rb
include in user-agent:
- sdk version
- ruby version
- platform it is running on
did not use RUBY_DESCRIPTION as it is a bit too verbose.
I would recommend getting this change in place, merged and released before #152 is merged. This should allow some sort of telemetry being in place.
I don't believe it is in the user's interest to hide this information from the server. Eventually, maybe, one could consider adding this to the registration phase in the payload as well.
> feat: make user-agent headers more descriptive

- .github/workflows/pull_request.yml
so it uses Node.js 20, as version 16 is getting deprecated.
coverallsapp also needs to be updated, but it doesn't run in v20 upstream, so not much to do there.
> chore: update github action

- .github/workflows/pull_request.yml
- .rubocop.yml
- README.md
- unleash-client.gemspec
As these have been EOL for many years now, and they no longer even build in modern macos. You really shouldn't be using this version of ruby at this day and age.
Expect support for MRI 2.7 and 3.0 to also be dropped in the future, as they are also EOL.
I think it is ok to wait a bit more until depcecating MRI 2.6, 2.7 and 3.0... and Jruby 9.3 (which targets to be compatible with  MRI 2.6).
This fixes the current builds breaking due to the 2.5/9.2 version of ruby not even building in the latest macos builders, and feels like the cleanest solution to get the builds going again.
> chore: no longer support MRI ruby 2.5 and jruby 9.2

- lib/unleash/context.rb
- Refactored the `to_s` method in the `Context` class to dynamically include all instance variables.
- This change ensures that any new instance variables added in the future will automatically be included in the string representation without needing to modify the `to_s` method.
- This makes the method more flexible and maintainable.
RSpec and RuboCop were executed, and no issues were found related to this change.
Closes #172
- `lib/unleash/context.rb`
- None at this time.
> Unleash::Context#to_s displays all properties

- lib/unleash/client.rb
- lib/unleash/metrics_reporter.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/metrics_reporter_spec.rb
Adds engine metadata to both registration and metrics
> feat: extend metrics data

- README.md
- examples/bootstrap.rb
- examples/simple.rb
- lib/unleash/configuration.rb
- spec/unleash/bootstrap/handler_spec.rb
- spec/unleash/client_spec.rb
- spec/unleash/metrics_reporter_spec.rb
- spec/unleash/scheduled_executor_spec.rb
https://linear.app/unleash/issue/2-2392/make-instance-id-autogenned-ruby
This makes `instance_id` an automatically generated read-only property, instead of being set by the user.
Similar to https://github.com/Unleash/unleash-client-dotnet/pull/226
> feat: automatically generated instance_id

- README.md
> docs: update versions in README.md

- README.md
- examples/bootstrap.rb
- examples/simple.rb
- lib/unleash/configuration.rb
- spec/unleash/bootstrap/handler_spec.rb
- spec/unleash/client_spec.rb
- spec/unleash/metrics_reporter_spec.rb
- spec/unleash/scheduled_executor_spec.rb
https://linear.app/unleash/issue/2-2429/revert-autogenned-instance-id-ruby
Reverts: #179
> chore: Revert "feat: automatically generated instance_id (#179)"

- lib/unleash/strategies.rb
This emits a std error line when overriding a built in strategy. That's not good behavior. This is just being polite and giving users some breathing room to stop doing that
This is a bit hacky but the intent here is to get people off this behavior so we can merge Yggdrasil (this is effectively the only breaking change that Yggdrasil will cause). Ultimately this code will go away anyway when that's merged so... eh
> chore: emit warning when overriding a built in strategy

- lib/unleash/client.rb
I added an optional second parameter Unleash&.segment_cache to the initialization of the method `Unleash::FeatureToggle.new(toggle_as_hash, Unleash&.segment_cache)`.
Is there another alternative for segments to be considered when querying variant ?
> feat: add segments to new feature toggle

- lib/unleash/feature_toggle.rb
- lib/unleash/spec_version.rb
- lib/unleash/variant.rb
- spec/unleash/configuration_spec.rb
https://linear.app/unleash/issue/2-2638/feature-enabled-support-in-ruby-sdk
Adds a `feature_enabled` property to variants, similar to https://github.com/Unleash/unleash-client-python/pull/285
Also bumps the client spec to the respective version, so the expectation matches.
> chore: add feature_enabled property to variants

- lib/unleash/feature_toggle.rb
- lib/unleash/spec_version.rb
- spec/unleash/configuration_spec.rb
https://linear.app/unleash/issue/2-2644/correctly-resolve-variant-stickiness-from-strategy-in-ruby-sdk
When bumping the client spec in https://github.com/Unleash/unleash-client-ruby/pull/197 to the latest version I noticed we were not being 100% compliant. The reason for it seemed to be the fact that we're not respecting custom strategy stickiness when resolving variants, as running the spec tests multiple times sometimes returned the wrong variant in those tests.
See:
- https://github.com/Unleash/unleash-client-node/pull/570
- https://github.com/Unleash/unleash-client-dotnet/pull/212
This PR applies a similar change to the Ruby SDK, bumping the client spec to the latest version.
> fix: variant stickiness from strategy

- README.md
This is to make sure others don't miss the Rails instructions, like I did (and apparently many of customers still do)
@melindafekete I added `1.a`, `1.b`, etc to show that there are different options, but happy to hear another idea
> Added TOC and tidy-up readme

- README.md
Variant fallback docs now state that the fallback will be returned when no flag is found on the server, rather than no variant being found on the server
> docs: variant fallback fix

- lib/unleash/strategy/flexible_rollout.rb
- spec/unleash/strategy/flexible_rollout_spec.rb
Same fix as done in some other sdks, such as the node one at
https://github.com/Unleash/unleash-client-node/pull/417
Fixes an issue where 1% rollout would not yield any results with
random rollout for certain group ids
> fix: update ruby SDK to increase the possible random numbers used for stickiness id

- CHANGELOG.md
- README.md
- lib/unleash/context.rb
- lib/unleash/version.rb
- spec/unleash/context_spec.rb
Previously we weren't passing the options which causes an incorrect number of args error
> fix: context now dumps to JSON correctly

- lib/unleash/version.rb
- unleash-client.gemspec
Resolves Yggdrasil core to a version that contains the correct binary for aarch64
> fix: aarch64 support

- lib/unleash/util/http.rb
Ruby's file writing defaults to utf-8, but net http's response seems to be based on the header and ASCII is used by default when no specification is made.
I didn't write any test files, but I verified them as follows:
```
bin/spring stop
bin/rails c
> Unleash::Client.new
[Unleash] ERROR: Unable to save backup file. Exception thrown Encoding::UndefinedConversionError:'"\xE3" from ASCII-8BIT to UTF-8'
...
bin/spring stop
bin/rails c
> Unleash::Client.new
(no error)
```
Closes  #214
> fix: response encode mismatch

- README.md
- lib/unleash/metrics_reporter.rb
- spec/unleash/metrics_reporter_spec.rb
This PR adds a test to validate what happens when metrics are empty for more than 10 minutes. This other PR #218 tested that it was actually failing.
We've also validated that nil bucket returns a 400 from Unleash server side so instead we should always fallback to an empty bucket.
> Handle empty metrics after 10 min

- .github/workflows/pull_request.yml
- lib/unleash/spec_version.rb
- spec/unleash/client_specification_spec.rb
- spec/unleash/configuration_spec.rb
- unleash-client.gemspec
Bumps client spec to 5.1.9 so we can confirm unicode characters work with Yggdrasil on Windows
> chore: bump client spec to 5.1.9

- lib/unleash/configuration.rb
- spec/unleash/client_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/metrics_reporter_spec.rb
This PR adds standardised client identification headers to the feature and metrics calls that the client makes to Unleash. The headers are:
- `x-unleash-appname`: the name of the application that is using the client. `UNLEASH-APPNAME` will be deleted in another PR (expand/contract pattern)
- `x-unleash-connection-id`: an internal unique identifier for the current instance of the client generated by the built-in crypto lib
- `x-unleash-sdk`: sdk information in the format `unleash-ruby@<version>` following reference `unleash-node@<version>` naming pattern
All the headers are intended for the Unleash team so clients should not be affected.
The main use cases we have are:
* capacity planning by knowing the number of unique connections made to the backend API
* debugging misconfigured SDKs …
> feat: client identification headers

- lib/unleash/configuration.rb
- spec/unleash/client_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/metrics_reporter_spec.rb
We found that `unleash-client-lang:version` convention is used a lot so for the new header we can stick to it for now.
> fix: use existing convention for sdk name

- .github/workflows/pull_request.yml
- README.md
- unleash-client.gemspec
Add github actions test also in the latest ruby release.
> chore: add ruby 3.4 support in gh actions

- lib/unleash/toggle_fetcher.rb
Updated the response handling message for better clarity, including the response code at the error message.
> fix: expose the response code on the error message

- lib/unleash/client.rb
- lib/unleash/configuration.rb
- lib/unleash/metrics_reporter.rb
- lib/unleash/toggle_fetcher.rb
- lib/unleash/util/http.rb
- spec/unleash/client_spec.rb
- spec/unleash/configuration_spec.rb
- spec/unleash/metrics_reporter_spec.rb
- spec/unleash/toggle_fetcher_spec.rb
* synchronizing `refresh_interval` to be identical to other SDKs (15s for fetch toggles, it was 10s before despite docs claiming it's 15s)
* adding `unleash-interval` header to fetch toggles call and send metric call (they are different so can't share HTTP header setting)
* adding `connectionId` to registration payload and send metrics payload
Please check toggle_fetcher and metrics_reporter since I added "seams" in those 2 in order to inject different metrics interval headers.
> feat: unleash-interval header

- lib/unleash/bootstrap/handler.rb
- lib/unleash/context.rb
- lib/unleash/metrics_reporter.rb
- unleash-client.gemspec
CI uses latest and dev is lagging, which gives a very unpleasant surprise when you land your PR on Github and suddenly Rubocop has _**opinions**_
This is just an update to Rubocop 1.75 + apply Rubocop fixes
> chore: update rubocop

- lib/unleash/metrics_reporter.rb
- spec/unleash/metrics_reporter_spec.rb
Fixes an issue where the SDK would attempt to report an empty bucket but would send a format that lacked everything Unleash needed to process it and would continue to do that every `metrics_interval` until the SDK received an evaluation for a toggle.
Needs [this](https://github.com/Unleash/unleash-client-ruby/pull/240) to pass
> fix: metrics no longer fails after 10 minutes in a loop

- unleash-client.gemspec
Relax `logger` gem dependency, so unleash can be used with logger >= 1.6.5.
This should allow using unleash gem with [logger 1.7.0](https://github.com/ruby/logger/releases/tag/v1.7.0) (which was released in 26/March).
Tests seem to pass locally.
> Relax logger dependency

- CHANGELOG.md
- README.md
- lib/unleash/version.rb
Bump to version 6.3.0 to incorporate #239.
> chore: bump version to 6.3.0

- unleash-client.gemspec
Update base64 dependency from v0.2.0 to v0.3.0.
Hello, my project is using unleash-client-ruby on AWS lambda. 
ruby runtime image of AWS lambda was updated and it makes install base64 gem with v0.3.0 into latest ruby3.4 runtime image. 
So, when we use unleash-client-ruby gem with AWS lambda latest runtime image, starting application is fails due to base64 version is conflicted.
So I'd like to update base64 dependency to v0.3.0
- unleash-client.gemspec
> update base64 gem to 0.3.0

- README.md
After renaming the repository, this updates internal references.
Additionally, includes the banner explaining about Unleash that we're adding to all official repositories.
> chore: rename repo references and add Unleash banner
