lib/unleash/client.rb
https://gitlab.com/gitlab-org/gitlab-ce/issues/53031
=> Avoid toggles nil exception

README.md, bin/unleash-client, examples/simple.rb, lib/unleash/scheduled_executor.rb, spec/unleash/scheduled_executor_spec.rb
Useful to test manually what is the status of a FeatureToggle.
=> Initial implementation of a CLI for the unleash client

.rubocop.yml, .travis.yml, README.md, bin/unleash-client, lib/unleash/client.rb, lib/unleash/configuration.rb, lib/unleash/context.rb, lib/unleash/feature_toggle.rb, lib/unleash/metrics.rb, lib/unleash/strategy/application_hostname.rb, lib/unleash/strategy/util.rb, lib/unleash/toggle_fetcher.rb, lib/unleash/variant.rb, lib/unleash/variant_definition.rb, lib/unleash/variant_override.rb, spec/unleash/client_spec.rb, spec/unleash/client_specification_spec.rb, spec/unleash/configuration_spec.rb, spec/unleash/context_spec.rb, spec/unleash/feature_toggle_spec.rb, spec/unleash/metrics_spec.rb, spec/unleash/variant_override_spec.rb, unleash-client.gemspec
Added/Improved:
- unit tests for variations
- tests for metrics
- documentation
- some code clean up
=> Implement variations

.travis.yml, README.md, unleash-client.gemspec
This PR is a follow up from PR #43
=> Support ruby 3

lib/unleash/toggle_fetcher.rb
=> fix: support SDK format v1 or higher

lib/unleash/configuration.rb, spec/unleash/configuration_spec.rb
=> fix: use standard refresh and metrics interval (#57)

README.md, lib/unleash/configuration.rb, spec/unleash/configuration_spec.rb
Implements feature described in issue #38
=> feat: Add support for filtering toggles on project (#38)

README.md
README is wrong about default log level
=> Fix README.md: default log level is WARN

.github/workflows/pull_request.yml, .rubocop.yml, bin/unleash-client, examples/simple.rb, lib/unleash/client.rb, lib/unleash/strategy/application_hostname.rb, spec/spec_helper.rb, spec/unleash/client_spec.rb, unleash-client.gemspec
and add reviewDog to help ensure we keep good code quality.
=> Fix rubocop warnings

lib/unleash/strategy/remote_address.rb, spec/unleash/strategy/remote_address_spec.rb
TODO:
- make rubocop happy
- format tests better, right now they are bundled in a way that doesn't make a lot of sense.
=> feature: add support for cidr in RemoteAddress strategy

README.md
=> doc: Add usage info for rails console and sidekiq

lib/unleash/version.rb
=> bump version for release 4.4.2

README.md, bin/console, spec/unleash/client_spec.rb
- fixed typos in docs
- updated docs on use of `is_disabled?` / `disabled?` / `if_disabled`
- expanded test coverage on new methods above
- fixed `bin/console` (only helpful when developing the SDK itself)
=> chore: update docs, add/improve tests, fix console

CHANGELOG.md
- Updates Changelog links
Closes #
=> chore: updates links in changelog

lib/unleash/constraint.rb, spec/unleash/constraint_spec.rb
The current implementation causes a type error if there is a date time in the current time. According to the [spec document](https://docs.getunleash.io/reference/unleash-context#structure), both should be possible, so we modified the implementation to allow the date time to also be passed.
Closes #
=> fix: Unexpected TypeError on constraint

CHANGELOG.md, lib/unleash/version.rb
=> chore: bump version + changelog for 5.0.3

lib/unleash/constraint.rb
This PR should help by removing side effects on the context and the constraint value.
I still want to leave the duplication of the constraint value as custom strategies might have side effects on it.
=> Simplify and avoid modifying the context value

lib/unleash/version.rb
=> chore: bump version to 5.0.6

CHANGELOG.md, lib/unleash/version.rb
Also includes the missing changelogs
=> chore: bump version to 5.0.7

CHANGELOG.md, README.md, lib/unleash/version.rb
Bumps version to 5.1.0 to prepare for the new release.
=> chore: bump version to 5.1.0

CHANGELOG.md, README.md, lib/unleash/version.rb
=> chore: bump version to 6.1.0

CHANGELOG.md, lib/unleash/version.rb
=> chore: bump version to 6.1.1

CHANGELOG.md, lib/unleash/version.rb
=> chore: bump version to 6.1.2

.github/workflows/pull_request.yml
=> chore: remve gh-action slack notify

CHANGELOG.md, lib/unleash/version.rb
=> chore: bump version to 6.2.0

CHANGELOG.md, lib/unleash/version.rb
=> chore: bump version to 6.4.0
